"""Closed civil-domain vocabularies and schema constants."""

from __future__ import annotations

SCHEMA_VERSION = "1.0"
PROJECT_FILE_SUFFIX = ".s2c.json"
DEFAULT_SCALE_CHECK_WARNING_PERCENT = 1.0
DEFAULT_DUPLICATE_DISTANCE_M = 0.05
DEFAULT_CONFLICT_ELEVATION_M = 0.02

EXISTING_GROUND = "EXISTING_GROUND"
DESIGN_GRADE = "DESIGN_GRADE"
CONTOUR_ELEVATION = "CONTOUR_ELEVATION"
SLOPE_ANNOTATION = "SLOPE_ANNOTATION"
UTILITY_RIM = "UTILITY_RIM"
UTILITY_INVERT = "UTILITY_INVERT"
SLAB_ELEVATION = "SLAB_ELEVATION"
DIMENSION = "DIMENSION"
MATERIAL_THICKNESS = "MATERIAL_THICKNESS"
DRAWING_METADATA = "DRAWING_METADATA"
UNKNOWN_NUMERIC = "UNKNOWN_NUMERIC"
REVIEW_REQUIRED_TYPE = "REVIEW_REQUIRED"
REJECTED_TYPE = "REJECTED"

POINT_TYPES = frozenset(
    {
        EXISTING_GROUND,
        DESIGN_GRADE,
        CONTOUR_ELEVATION,
        SLOPE_ANNOTATION,
        UTILITY_RIM,
        UTILITY_INVERT,
        SLAB_ELEVATION,
        DIMENSION,
        MATERIAL_THICKNESS,
        DRAWING_METADATA,
        UNKNOWN_NUMERIC,
        REVIEW_REQUIRED_TYPE,
        REJECTED_TYPE,
    }
)
TERRAIN_POINT_TYPES = frozenset(
    {EXISTING_GROUND, DESIGN_GRADE, CONTOUR_ELEVATION}
)

UNREVIEWED = "UNREVIEWED"
AUTO_HIGH_CONFIDENCE = "AUTO_HIGH_CONFIDENCE"
APPROVED = "APPROVED"
EDITED_AND_APPROVED = "EDITED_AND_APPROVED"
REJECTED = "REJECTED"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
REVIEW_STATUSES = frozenset(
    {
        UNREVIEWED,
        AUTO_HIGH_CONFIDENCE,
        APPROVED,
        EDITED_AND_APPROVED,
        REJECTED,
        REVIEW_REQUIRED,
    }
)
APPROVED_STATUSES = frozenset({APPROVED, EDITED_AND_APPROVED})

MANUAL = "MANUAL"
PDF_TEXT = "PDF_TEXT"
PDF_VECTOR = "PDF_VECTOR"
LOCAL_OCR = "LOCAL_OCR"
MOCK_OCR = "MOCK_OCR"
SOURCE_METHODS = frozenset({MANUAL, PDF_TEXT, PDF_VECTOR, LOCAL_OCR, MOCK_OCR})

SYMBOL_TYPES = frozenset(
    {
        "EXISTING_CROSS",
        "PLUS_SIGN",
        "SURVEY_MARKER",
        "DESIGN_OVAL",
        "POINT_DOT",
        "LEADER_ENDPOINT",
        "UNKNOWN_SYMBOL",
        "MANUAL_POINT",
        "NONE",
    }
)

DESCRIPTION_BY_TYPE = {
    EXISTING_GROUND: "EX_GROUND",
    DESIGN_GRADE: "DESIGN_GRADE",
    CONTOUR_ELEVATION: "CONTOUR",
}

DEFAULT_PLAUSIBLE_ELEVATION_RANGE = (-1000.0, 10000.0)
MAX_SOURCE_BYTES = 250 * 1024 * 1024
MAX_SOURCE_PIXELS = 200_000_000
